# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
   #runs every 10 minutes
     # - cron: '*/10 * * * *'
   #runs every 2 days
    - cron: '39 2 */2 * *'

permissions:
  contents: write 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chromium and xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

        sudo snap install chromium --channel=126.0.6478.182/stable

        wget https://chromedriver.storage.googleapis.com/126.0.6478.182/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

        sudo apt-get install -y xvfb=2:21.1.4-2ubuntu1.7~22.04.11
        
    - name: Run main.py
      env: 
        RECEIVING_EMAIL: ${{ secrets.RECEIVING_EMAIL }}
        SENDING_EMAIL: ${{ secrets.SENDING_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          python src/main.py
